=== preston/fhir-controller/public/stack.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://stack.skycapp.com/stack.schema.json",
    "title": "FHIR Stack Controller Configuration Schema.",
    "description": "For configuration files used by FHIR stack controllers.",
    "type": "object",
    "required": [
        "title",
        "instructions",
        "data",
        "fhir_base_url",
        "links",
        "driver"
    ],
    "properties": {
        "title": {
            "description": "Very short name for the controller instance.",
            "type": "string"
        },
        "instructions": {
            "description": "Human-readable user instructinos for how to use this controller, in markdown format.",
            "type": "string"
        },
        "driver": {
            "description": "The specific FHIR server implementation.",
            "type": "string",
            "enum": [
                "generic",
                "hapi",
                "wildfhir",
                "fhircandle"
            ]
        },
        "data": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/data_file"
            }
        },
        "fhir_base_url": {
            "description": "Base URL for the FHIR server to use.",
            "type": "string"
        },
        "links": {
            "description": "Ordered list of links to other resources.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "url"
                ],
                "properties": {
                    "name": {
                        "description": "Human-readable name for the link.",
                        "type": "string"
                    },
                    "url": {
                        "description": "URL for the link.",
                        "type": "string"
                    }
                }
            }
        }
    },
    "$defs": {
        "data_file": {
            "type": "object",
            "description": "An absolute URL that must start with 'http://' or 'https://', or assumed to be a path relative to the application base URL.",
            "required": [
                "file",
                "load",
                "name",
                "description",
                "type"
            ],
            "properties": {
                "file": {
                    "description": "Name of a JSON FHIR data bundle file. Must be valid",
                    "type": "string"
                },
                "load": {
                    "description": "Whether or not to load the file by default.",
                    "type": "boolean"
                },
                "name": {
                    "description": "Human-readable name for the file. May be the same as the file name.",
                    "type": "string"
                },
                "description": {
                    "description": "A description of the data contained in the file.",
                    "type": "string"
                },
                "type": {
                    "description": "A brief text label used for UI purposes only. Does not affect data loading or processing.",
                    "type": "string"
                }
            }
        }
    }
}

=== preston/fhir-controller/public/stack.json
{
    "$schema": "stack.schema.json",
    "title": "Example Stack Controller Configuration",
    "instructions": "Provide usage instructions here in markdown format.",
    "fhir_base_url": "http://localhost:8080/fhir",
    "driver": "hapi",
    "links": [
        {
            "name": "FHIR Server",
            "url": "http://localhost:8080"
        }
    ],
    "data": [
        {
            "file": "data/example/hospitalInformation1671557337568.json",
            "load": true,
            "name": "Organization Bundle 1",
            "description": "Synthea-generated Organization records",
            "type": "Organization Bundle",
            "priority": 0
        },
        {
            "file": "data/example/hospitalInformation1671557444542.json",
            "load": true,
            "name": "Organization Bundle 2",
            "description": "Synthea-generated Organization records",
            "type": "Organization Bundle",
            "priority": 1
            
        },
        {
            "file": "data/example/practitionerInformation1671557337568.json",
            "load": true,
            "name": "Practioner Bundle 1",
            "description": "Synthea-generated Practitioner records",
            "type": "Practitioner Bundle",
            "priority": 2
        },
        {
            "file": "data/example/practitionerInformation1671557444542.json",
            "load": true,
            "name": "Practioner Bundle2 ",
            "description": "Synthea-generated Practitioner records",
            "type": "Practitioner Bundle",
            "priority": 3
        },
        {
            "file": "data/example/Patient 1 - Adrian Allen1.json",
            "load": true,
            "name": "Patient 1 - Adrian Allen1",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 4
        },
        {
            "file": "data/example/Patient 2 - Beth Brooks2.json",
            "load": true,
            "name": "Patient 2 - Beth Brooks2",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 5
        },
        {
            "file": "data/example/Patient 3 - Carmen Chavez.json",
            "load": true,
            "name": "Patient 3 - Carmen Chavez",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 6
        },
        {
            "file": "data/example/Patient 4 - Diana Dixon4.json",
            "load": true,
            "name": "Patient 4 - Diana Dixon4",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 7
        }
    ]
}
