=== preston/fhir-controller/src/assets/stack.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://stack.skycapp.com/stack.schema.json",
    "title": "FHIR Stack Controller Configuration Schema.",
    "description": "For configuration files used by FHIR stack controllers.",
    "type": "object",
    "required": [
        "title",
        "instructions",
        "data",
        "fhir_base_url",
        "links",
        "driver"
    ],
    "properties": {
        "title": {
            "description": "Very short name for the controller instance.",
            "type": "string"
        },
        "instructions": {
            "description": "Human-readable user instructinos for how to use this controller, in markdown format.",
            "type": "string"
        },
        "driver": {
            "description": "The specific FHIR server implementation.",
            "type": "string",
            "enum": [
                "generic",
                "hapi",
                "wildfhir",
                "fhircandle"
            ]
        },
        "data": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/data_file"
            }
        },
        "fhir_base_url": {
            "description": "Base URL for the FHIR server to use.",
            "type": "string"
        },
        "links": {
            "description": "Ordered list of links to other resources.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "url"
                ],
                "properties": {
                    "name": {
                        "description": "Human-readable name for the link.",
                        "type": "string"
                    },
                    "url": {
                        "description": "URL for the link.",
                        "type": "string"
                    }
                }
            }
        }
    },
    "$defs": {
        "data_file": {
            "type": "object",
            "description": "Any absolute URLs must start with 'http://' or 'https://'. Otherwise, they are assumed to be a path relative from where your .json configuration file is loaded.",
            "required": [
                "file",
                "load",
                "loader",
                "name",
                "description",
                "type",
                "priority"
            ],
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "loader": {
                                "const": "cql-as-fhir-library"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "evaluate"
                        ]
                    }
                }
            ],
            "properties": {
                "file": {
                    "description": "Name of a JSON FHIR data bundle file. Must be valid",
                    "type": "string"
                },
                "load": {
                    "description": "Whether or not to load the file by default.",
                    "type": "boolean"
                },
                "loader": {
                    "description": "Load function to use for this file. Default: 'fhir-bundle'.",
                    "type": "string",
                    "enum": [
                        "fhir-bundle",
                        "cql-as-fhir-library"
                    ],
                    "default": "fhir-bundle"
                },
                "name": {
                    "description": "Human-readable name for the file. May be the same as the file name.",
                    "type": "string"
                },
                "description": {
                    "description": "A description of the data contained in the file.",
                    "type": "string"
                },
                "type": {
                    "description": "A brief text label used for UI purposes only. Does not affect data loading or processing.",
                    "type": "string"
                },
                "priority": {
                    "description": "The order in which to load the data files. Lower numbers are loaded first.",
                    "type": "integer",
                    "default": 1
                },
                "evaluate": {
                    "$ref": "#/$defs/evaluate",
                    "description": "Optional evaluation parameters for CQL libraries. Only used if the loader is 'cql-as-fhir-library'."
                }
            }
        },
        "evaluate": {
            "type": "object",
            "description": "Optional evaluation parameters for CQL libraries.",
            "required": [
                "id",
                "subjects"
            ],
            "properties": {
                "id": {
                    "description": "The ID of the CQL library to evaluate.",
                    "type": "string"
                },
                "subjects": {
                    "description": "The subjects to evaluate the CQL library against.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "description": "A subject to evaluate the CQL library against.",
                        "required": [
                            "id",
                            "name"
                        ],
                        "properties": {
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== preston/fhir-controller/src/assets/stack.json
{
    "$schema": "stack.schema.json",
    "title": "Example Configuration",
    "instructions": "Provide usage instructions here in markdown format.",
    "fhir_base_url": "http://localhost:8080/fhir",
    "driver": "hapi",
    "links": [
        {
            "name": "FHIR Server",
            "url": "http://localhost:8080"
        }
    ],
    "data": [
        {
            "file": "data/example/fhir/hospitalInformation1671557337568.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Organization Bundle 1",
            "description": "Synthea-generated Organization records",
            "type": "Organization Bundle",
            "priority": 0
        },
        {
            "file": "data/example/fhir/hospitalInformation1671557444542.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Organization Bundle 2",
            "description": "Synthea-generated Organization records",
            "type": "Organization Bundle",
            "priority": 1
        },
        {
            "file": "data/example/fhir/practitionerInformation1671557337568.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Practioner Bundle 1",
            "description": "Synthea-generated Practitioner records",
            "type": "Practitioner Bundle",
            "priority": 2
        },
        {
            "file": "data/example/fhir/practitionerInformation1671557444542.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Practioner Bundle2 ",
            "description": "Synthea-generated Practitioner records",
            "type": "Practitioner Bundle",
            "priority": 3
        },
        {
            "file": "data/example/fhir/Patient 1 - Adrian Allen1.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Patient 1 - Adrian Allen1",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 4
        },
        {
            "file": "data/example/fhir/Patient 2 - Beth Brooks2.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Patient 2 - Beth Brooks2",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 5
        },
        {
            "file": "data/example/fhir/Patient 3 - Carmen Chavez.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Patient 3 - Carmen Chavez",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 6
        },
        {
            "file": "data/example/fhir/Patient 4 - Diana Dixon4.json",
            "load": true,
            "loader": "fhir-bundle",
            "name": "Patient 4 - Diana Dixon4",
            "description": "Deidentified patient record from SHARES study.",
            "type": "Patient Bundle",
            "priority": 7
        },
        {
            "file": "data/example/cql/HelloWorld.cql",
            "load": true,
            "loader": "cql-as-fhir-library",
            "name": "HelloWorld CQL Library",
            "description": "CQL library for testing purposes.",
            "type": "CQL Library",
            "priority": 8,
            "evaluate": {
                "id": "HelloWorld",
                "subjects": [
                    {
                        "id": "cfsb1703736930464",
                        "name": "Adrian Allen"
                    },
                    {
                        "id": "cfsb1699034947598",
                        "name": "Beth Brooks"
                    },
                    {
                        "id": "cfsb1700025838491",
                        "name": "Carmen Chavez"
                    },
                    {
                        "id": "cfsb1700154185275",
                        "name": "Diana Dixon"
                    }
                ]
            }
        }
    ]
}
